
name: ipytone-docs
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - numpy
  - sphinx
  - pydata-sphinx-theme
  - matplotlib-base
  - myst-nb
  - yarn<=1
  - jupyterlite-core
  - jupyterlite-sphinx
  - jupyterlite-xeus-python
  - pip
  - pip:
    # installs ipytone in editable mode (relative path)
    - -e ..
