
name: ipytone-docs
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - numpy
  - sphinx
  - pydata-sphinx-theme
  - matplotlib-inline
  - myst-nb
  - yarn
  - pip:
    - jupyterlite
    - jupyterlite-sphinx
