
name: ipytone-docs
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - ipytone
  - numpy
  - sphinx
  - pydata-sphinx-theme
  - matplotlib-base
  - myst-nb
  - yarn
  - empack
  - pip
  - pip:
    - jupyterlite
    - jupyterlite-sphinx
    - jupyterlite-xeus-python
    # installs ipytone in editable mode (relative path)
    # - -e ..
