
name: ipytone-docs
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - numpy
  - sphinx
  - pydata-sphinx-theme
  - emsdk
  - pip:
    - jupyterlite
    - jupyterlite-sphinx
    - jupyterlite-xeus-python==0.3.0
    - empack
