name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python via conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          auto-activate-base: true
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install pip twine setuptools wheel jupyterlab=3 jupyter-packaging python-build nodejs yarn
      - name: Build and publish
        shell: bash -l {0}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build . --no-isolation
          twine upload dist/ipytone-*
