name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  py:
    name: Python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ipytone-dev
        environment-file: environment-dev.yml
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-activate-base: false
        channels: conda-forge
    - name: Install ipytone
      run: pip install . -v
    - name: Run Python tests
      run: pytest .
