name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  py:
    name: Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies + ipytone
      run: |
        python -m pip install --upgrade -v -e ".[test]"

    - name: Run Python tests
      run: |
        python -m pytest ipytone -vv --color=yes
